apiVersion: v1
kind: Service
metadata:
  name: webappexampleext
  labels:
    app: webappexample
spec:
  selector:
    app: webappexample
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80       # Port exposed publicly
      targetPort: 3333