apiVersion: v1
kind: Service
metadata:
  name: webappexample
  labels:
    app: webappexample  # This label is crucial for ServiceMonitor
spec:
  selector:
    app: webappexample
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 3333
    nodePort: 30000
    protocol: TCP